# Generated by Django 2.2 on 2019-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqsupplierdetail',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
    ]
