# Generated by Django 2.2 on 2019-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190511_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdetailsupplier',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dcheadersupplier',
            name='dc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podetailsupplier',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poheadersupplier',
            name='po_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationdetailsupplier',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationheadersupplier',
            name='quotation_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rfqsupplierheader',
            name='rfq_no',
            field=models.CharField(max_length=100),
        ),
    ]
