# Generated by Django 2.2 on 2019-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_quotationdetailsupplier_quotation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationheadersupplier',
            name='currency',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationheadersupplier',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=8),
            preserve_default=False,
        ),
    ]
