# Generated by Django 2.2 on 2019-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190511_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcheadersupplier',
            name='mrn_status',
        ),
        migrations.AddField(
            model_name='dcdetailsupplier',
            name='accpeted_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcdetailsupplier',
            name='returned_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
