# Generated by Django 2.2 on 2019-05-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20190512_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcdetailsupplier',
            old_name='accpeted_quantity',
            new_name='accepted_quantity',
        ),
    ]
