# Generated by Django 2.2 on 2019-05-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_podetailsupplier_poheadersupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcHeaderSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_no', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DcDetailSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(max_length=100)),
                ('mrn_status', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('dc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.PoHeaderSupplier')),
            ],
        ),
    ]
