# Generated by Django 2.2 on 2019-05-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_dcdetailsupplier_dcheadersupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdetailsupplier',
            name='dc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.DcHeaderSupplier'),
        ),
    ]
