# Generated by Django 2.2 on 2019-05-02 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20190502_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcheadersupplier',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
