# Generated by Django 2.2 on 2019-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_dcheadersupplier_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdetailsupplier',
            name='mrn_status',
        ),
        migrations.AddField(
            model_name='dcheadersupplier',
            name='mrn_status',
            field=models.CharField(default='Pending', max_length=100),
            preserve_default=False,
        ),
    ]
