# Generated by Django 2.2 on 2019-05-03 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RfqCustomerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attn', models.CharField(max_length=100)),
                ('follow_up', models.DateField(blank=True)),
                ('show_notification', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RfqCustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('rfq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.RfqCustomerHeader')),
            ],
        ),
    ]
