# Generated by Django 2.2 on 2019-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcheadercustomer',
            name='mrn_status',
        ),
        migrations.AddField(
            model_name='dcdetailcustomer',
            name='accepted_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcdetailcustomer',
            name='returned_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dcdetailcustomer',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dcheadercustomer',
            name='dc_no',
            field=models.CharField(max_length=100),
        ),
    ]
