# Generated by Django 2.2 on 2019-08-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190801_0540'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcheadersupplier',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AlterField(
            model_name='poheadersupplier',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AlterField(
            model_name='quotationheadersupplier',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AlterField(
            model_name='rfqsupplierheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.DeleteModel(
            name='Company_info',
        ),
    ]
