# Generated by Django 2.2 on 2019-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcheadersupplier',
            name='show_notification',
            field=models.BooleanField(default=True),
        ),
    ]
