# Generated by Django 2.2 on 2019-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='company_address',
            field=models.TextField(),
        ),
    ]
