# Generated by Django 2.2 on 2019-08-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('supplier', '0002_auto_20190801_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdetailsupplier',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='dcdetailsupplier',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='dcdetailsupplier',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='podetailsupplier',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='podetailsupplier',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='podetailsupplier',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='quotationdetailsupplier',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='quotationdetailsupplier',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='quotationdetailsupplier',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='rfqsupplierdetail',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='rfqsupplierdetail',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='rfqsupplierdetail',
            name='item_name',
        ),
        migrations.AddField(
            model_name='dcdetailsupplier',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Add_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetailsupplier',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Add_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationdetailsupplier',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Add_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqsupplierdetail',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Add_products'),
            preserve_default=False,
        ),
    ]
