# Generated by Django 2.2 on 2019-05-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190528_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='company_logo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
