# Generated by Django 2.2 on 2019-05-20 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_no', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('ntn', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('footer_description', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('cartage_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('withholding_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.PurchaseHeader')),
            ],
        ),
    ]
