# Generated by Django 2.2 on 2019-08-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_info'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='purchasereturnheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='salereturnheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='voucherheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
    ]
