# Generated by Django 2.2 on 2019-07-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ref_inv_tran_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.VoucherHeader'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ref_inv_tran_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
