# Generated by Django 2.2 on 2019-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='voucher_no',
            field=models.CharField(default='0001', max_length=100),
            preserve_default=False,
        ),
    ]
