# Generated by Django 2.2 on 2019-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='cnic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='stn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
