# Generated by Django 2.2 on 2019-07-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190721_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetail',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.SaleHeader'),
        ),
    ]
