# Generated by Django 2.2 on 2019-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_purchaseheader_purchase_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='unit',
            field=models.CharField(default='pcs', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='item_description',
            field=models.TextField(),
        ),
    ]
