# Generated by Django 2.2 on 2019-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactions_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='refrence_id',
            field=models.CharField(max_length=100),
        ),
    ]
