# Generated by Django 2.2 on 2019-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_cartage_and_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='hs_code',
        ),
        migrations.AddField(
            model_name='saleheader',
            name='hs_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
