# Generated by Django 2.2 on 2019-06-27 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_saledetail_dc_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=100)),
                ('doc_date', models.DateField(default=datetime.date.today)),
                ('cheque_no', models.CharField(max_length=100)),
                ('cheque_date', models.DateField(max_length=datetime.date.today)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='voucher_no',
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount')),
            ],
        ),
    ]
