# Generated by Django 2.2 on 2019-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190814_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saledetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
