# Generated by Django 2.2 on 2019-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190721_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='voucher_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
