# Generated by Django 2.2 on 2019-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190815_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='purchase_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasereturnheader',
            name='purchase_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='sale_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salereturnheader',
            name='sale_no',
            field=models.CharField(max_length=100),
        ),
    ]
