# Generated by Django 2.2 on 2019-06-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190627_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherheader',
            name='voucher_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
