# Generated by Django 2.2 on 2019-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190818_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='dcdetailid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
