# Generated by Django 2.2 on 2019-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transactions_voucher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='account_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
