# Generated by Django 2.2 on 2019-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_chartofaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_id',
            field=models.CharField(max_length=100),
        ),
    ]
