# Generated by Django 2.2 on 2019-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_purchaseheader_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='follow_up',
            field=models.DateField(blank=True, default='2010-06-10'),
            preserve_default=False,
        ),
    ]
