# Generated by Django 2.2 on 2019-09-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190831_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='hs_code',
            new_name='dcdetailid',
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salereturnheader',
            name='sale_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salereturndetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
