# Generated by Django 2.2 on 2019-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_saleheader_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='credit_days',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturnheader',
            name='credit_days',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleheader',
            name='credit_days',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salereturnheader',
            name='credit_days',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
