# Generated by Django 2.2 on 2019-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190730_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetail',
            name='invoice_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
