# Generated by Django 2.2 on 2019-05-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_chartofaccount_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='account_type',
        ),
    ]
