# Generated by Django 2.2 on 2019-05-28 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_remove_chartofaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence_id', models.IntegerField()),
                ('refrence_date', models.DateField(default=datetime.date.today)),
                ('account_id', models.IntegerField()),
                ('tran_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
