# Generated by Django 2.2 on 2019-07-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190622_0805'),
        ('transaction', '0010_auto_20190710_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='item_code',
            new_name='dc_ref',
        ),
        migrations.RenameField(
            model_name='salereturndetail',
            old_name='item_name',
            new_name='hs_code',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='salereturndetail',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='salereturndetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='purchasereturndetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
    ]
