# Generated by Django 2.2 on 2019-07-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_voucherheader_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetail',
            name='header_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='transaction.VoucherHeader'),
            preserve_default=False,
        ),
    ]
