# Generated by Django 2.2 on 2019-08-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DcDetailCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('accepted_quantity', models.IntegerField()),
                ('returned_quantity', models.IntegerField()),
                ('po_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DcHeaderCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_no', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('footer_remarks', models.TextField()),
                ('show_notification', models.BooleanField(default=True)),
                ('follow_up', models.DateField(blank=True)),
                ('cartage_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoDetailCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(max_length=100)),
                ('quotation_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoHeaderCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attn', models.CharField(max_length=100)),
                ('prc_basis', models.CharField(max_length=100)),
                ('po_client', models.CharField(max_length=100)),
                ('leadtime', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('follow_up', models.DateField(blank=True)),
                ('show_notification', models.BooleanField(default=True)),
                ('footer_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetailCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHeaderCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attn', models.CharField(max_length=100)),
                ('prc_basis', models.CharField(max_length=100)),
                ('leadtime', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('yrref', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('follow_up', models.DateField(blank=True)),
                ('show_notification', models.BooleanField(default=True)),
                ('footer_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RfqCustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RfqCustomerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attn', models.CharField(max_length=100)),
                ('follow_up', models.DateField(blank=True)),
                ('show_notification', models.BooleanField(default=True)),
                ('footer_remarks', models.TextField()),
            ],
        ),
    ]
