# Generated by Django 2.2 on 2019-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetailcustomer',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
    ]
