# Generated by Django 2.2 on 2019-08-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqcustomerheader',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount'),
        ),
        migrations.AddField(
            model_name='rfqcustomerheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='rfqcustomerheader',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqcustomerdetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='rfqcustomerdetail',
            name='rfq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.RfqCustomerHeader'),
        ),
        migrations.AddField(
            model_name='quotationheadercustomer',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount'),
        ),
        migrations.AddField(
            model_name='quotationheadercustomer',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='quotationheadercustomer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationdetailcustomer',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='quotationdetailcustomer',
            name='quotation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.QuotationHeaderCustomer'),
        ),
        migrations.AddField(
            model_name='poheadercustomer',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount'),
        ),
        migrations.AddField(
            model_name='poheadercustomer',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='poheadercustomer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podetailcustomer',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='podetailcustomer',
            name='po_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.PoHeaderCustomer'),
        ),
        migrations.AddField(
            model_name='dcheadercustomer',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount'),
        ),
        migrations.AddField(
            model_name='dcheadercustomer',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
        migrations.AddField(
            model_name='dcheadercustomer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcdetailcustomer',
            name='dc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.DcHeaderCustomer'),
        ),
        migrations.AddField(
            model_name='dcdetailcustomer',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Company_info'),
        ),
    ]
