# Generated by Django 2.2 on 2019-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190629_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationheadercustomer',
            name='yrref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
