# Generated by Django 2.2 on 2019-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_quotationheadercustomer_yrref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poheadercustomer',
            old_name='yrref',
            new_name='po_client',
        ),
    ]
