# Generated by Django 2.2 on 2019-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190808_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdetailcustomer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
