# Generated by Django 2.2 on 2019-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190827_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdetailcustomer',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
