# Generated by Django 2.2 on 2019-07-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190625_0959'),
        ('customer', '0005_auto_20190701_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfqcustomerdetail',
            old_name='item_code',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='rfqcustomerdetail',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='rfqcustomerdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rfqcustomerdetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='rfqcustomerheader',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Company_info'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Company_info')),
            ],
        ),
    ]
