# Generated by Django 2.2 on 2019-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_quotationheadercustomer_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqcustomerdetail',
            name='item_description',
        ),
        migrations.AddField(
            model_name='rfqcustomerdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
