# Generated by Django 2.2 on 2019-07-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190708_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqcustomerdetail',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
    ]
