# Generated by Django 2.2 on 2019-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190708_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqcustomerdetail',
            name='remarks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
