# Generated by Django 2.2 on 2019-07-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rfqcustomerdetail_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqcustomerdetail',
            name='remarks',
        ),
    ]
