# Generated by Django 2.2 on 2019-07-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190622_0805'),
        ('customer', '0012_auto_20190708_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podetailcustomer',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='podetailcustomer',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='podetailcustomer',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='podetailcustomer',
            name='unit',
        ),
        migrations.AddField(
            model_name='podetailcustomer',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_products'),
        ),
        migrations.AlterField(
            model_name='podetailcustomer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quotationdetailcustomer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
