# Generated by Django 2.2 on 2019-07-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20190708_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdetailcustomer',
            name='unit_price',
        ),
    ]
