# Generated by Django 2.2 on 2019-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
