# Generated by Django 2.2 on 2019-05-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_products_opening_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='unit',
            field=models.CharField(default='pcs', max_length=100),
            preserve_default=False,
        ),
    ]
