# Generated by Django 2.2 on 2019-08-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_code', models.IntegerField()),
                ('sub', models.CharField(max_length=100)),
                ('main_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='add_products',
            name='category_id',
        ),
        migrations.AddField(
            model_name='add_products',
            name='main_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category'),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AddField(
            model_name='add_products',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.SubCategory'),
        ),
    ]
