# Generated by Django 2.2 on 2019-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190813_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='main_categoty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_products',
            name='sub_categoty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
