# Generated by Django 2.2 on 2019-09-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190903_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_products',
            old_name='main_categoty',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='add_products',
            old_name='sub_categoty',
            new_name='sub_category',
        ),
    ]
