# Generated by Django 2.2 on 2019-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='form_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
