# Generated by Django 2.2 on 2019-07-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userroles_form_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='print',
            new_name='r_print',
        ),
    ]
