# Generated by Django 2.2.3 on 2019-07-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190721_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='r_return',
            field=models.IntegerField(default='0'),
        ),
    ]
