# Generated by Django 2.2 on 2019-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userroles_r_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('is_current_year', models.IntegerField()),
            ],
        ),
    ]
