# Generated by Django 2.2.3 on 2019-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_fiscalyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='add',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='delete',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='display',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='edit',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='r_print',
            field=models.IntegerField(default='0'),
        ),
    ]
