# Generated by Django 2.2 on 2019-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_no', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('ntn', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='transaction_id',
            new_name='purchase_id',
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='account_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
