# Generated by Django 2.2 on 2019-05-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190520_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount'),
        ),
    ]
