# Generated by Django 2.2 on 2019-05-21 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190520_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('footer_description', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('cartage_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('withholding_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('unit', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.SaleHeader')),
            ],
        ),
    ]
