# Generated by Django 2.2 on 2019-05-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_purchasereturndetail_purchasereturnheader_salereturnheader_saleretutndetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleRetutnDetail',
            new_name='SaleReturnDetail',
        ),
    ]
